CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE Employee(
E_ID INT(25),
E_NAME VARCHAR(25),
AGE INT(10),
SALARY FLOAT(10),
PRIMARY KEY(E_ID));
INSERT INTO Employee VALUES (101,"ANU",22,9000);
INSERT INTO Employee VALUES (102,"SHANE",29,8000);
INSERT INTO Employee VALUES (103,"ROHAN",34,6000);
INSERT INTO Employee VALUES (104,"SCOTT",44,10000); 
INSERT INTO Employee VALUES (105,"TIGER",35,8000);
INSERT INTO Employee VALUES (106,"ALEX",27,7000);
INSERT INTO Employee VALUES (107,"ABHI",29,8000);  
SELECT COUNT(E_NAME) FROM Employee;
SELECT MAX(AGE) FROM Employee;
SELECT MIN(AGE) FROM Employee;
SELECT SUM(AGE) FROM Employee;
SELECT AVG(AGE) FROM Employee;

CREATE VIEW E_AGE AS 
SELECT E_NAME,AGE FROM Employee;

SELECT * FROM E_AGE;

SELECT E_NAME,SALARY FROM Employee GROUP BY E_NAME;


SELECT SALARY FROM Employee ORDER BY SALARY ASC;


SELECT SALARY FROM Employee ORDER BY SALARY DESC;





